name: Java CI against WF SNAPSHOT

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      # The wildfly and corresponding wildfly core versions used in WildFly master
      WILDFLY_VERSION: 19.0.0.Beta2-SNAPSHOT
      WILDFLY_CORE_VERSION: 11.0.0.Beta7
    steps:
    - name: Checkout feature pack
      uses: actions/checkout@v2
      with:
        path: main
    - name: Checkout wildfly master
      uses: actions/checkout@v2
      with:
        repository: wildfly/wildfly
        path: wildfly-master
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Version
      run: mvn --version
    - name: Current directory
      run: pwd ; ls -al
    - name: Build WildFly master
      run: mvn -B install -DskipTests
      working-directory: wildfly-master
    - name: Build
      run: mvn -B install -Dversion.org.wildfly=${WILDFLY_VERSION} -Dversion.org.wildfly.core=${WILDFLY_CORE_VERSION}
      working-directory: main
